# If you wanted to examine the exception, you can do it using the following syntax

try:
    x = int(input())
except ValueError as error:
    print(error)



